name: read_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.0.0
  # webview_flutter: ^4.0.7  # Remove after migration is complete

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon5.png"
  remove_alpha_ios: true
